# Graphics
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
GAME_FPS = 50
GAME_FRAME_MS = 1000 / GAME_FPS

# Physics
PHYSICS_TIME_STEP = (1.0 / GAME_FPS)
PHYSICS_NUM_VEL_ITERS = 6
PHYSICS_NUM_POS_ITERS = 2
PHYSICS_DEBUG_DRAW_BODIES = True

# Entities
SHIELD_MAX_ENERGY = 200
SHIP_MAX_ENERGY = 500
BULLET_VELOCITY = 0.05
BORDER_REPULSION_FORCE = 200
ASTEROID_VELOCITY = 80
SHIP_SCALE = 0.67
